CREATE TABLE students (
  student_id bigint generated by default as identity primary key,
  name text unique not null,
  face_embedding jsonb,
  voide_embedding jsonb
);
CREATE TABLE teachers (
  teacher_id bigint generated by default as identity primary key,
  name text,
  username text unique not null,
  password text not null
);
CREATE TABLE subjects (
  subject_id bigint generated by default as identity primary key,
  subject_code text not null,
  name text default 'UNKNOWN',
  section text default 'N/A',
  teacher_id bigint references teachers (teacher_id) on delete set null
);
CREATE TABLE student_subjects (
  subject_id bigint references subjects (subject_id) on delete cascade,
  student_id bigint references students (student_id) on delete cascade,
  primary key (subject_id, student_id)
);

CREATE TABLE attendance_logs (
  id bigint generated by default as identity primary key,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  is_present bool default true,
  subject_id bigint references subjects (subject_id) on delete cascade,
  student_id bigint references students (student_id) on delete cascade
);
